### ISSUE TITLE
to_ and write_geojson

### ISSUE THREAD

**Issue by RichMar** [jrasband-dev/pandas-geojson#4]
Hi, two weeks ago the to_geojson and write_geojson instructions stopped working. Was that the intention?

**Comment by jrasband-dev** [comment]
Hi @RichMar,

It sounds like you're referring to the recent major release where we changed some of the function names. My response is based on that assumption. Please feel free to correct me if I've misunderstood. 

We recently restructured the package and added a **`GeoJSON`** object. Many of the changes in function naming conventions centered on this new object. 

Instead of `to_geojson` we renamed the function `from_dataframe`. With the **`GeoJSON`** object as the central point of reference it made sense to switch to the function name to indicate the source of where the geojson data was coming from. 

`write_geojson` is now `save_geojson`. In hindsight, we could have left this function naming convention the same. Some python packages use `read` and `write` others use `read` and `save`. Save seemed more intuitive for users.

**Comment by RichMar** [comment]
Hello, yes, that was probably the reason, but I was no longer able to get it working with the new functions. I had to replace it with another package. But i forgot to remove the import pandas_geojson as pdg call from the code. And again from May it started giving an error:
import pandas_geojson as pdg
   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pandas_geojson/__init__.py", line 15, in <module>
     from pandas_geojson.io import (
   File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pandas_geojson/io.py", line 6, in <module>
     from pandas_geojson.parsers.kml import parse_kml_placemarks
ModuleNotFoundError: No module named 'pandas_geojson.parsers'
Error: Process completed with exit code 1.

I saw that you are already solving a problem, so I don't know if it is related to this.

**Comment by jrasband-dev** [comment]
I see the issue. a bit of the code for the next feature accidentally got included in there. I'll create a patch version and send it out ASAP. It will be version 2.2.1. Just out of curiosity, what package did you replace it with?

**Comment by RichMar** [comment]
I used [geopandas.geodataframe](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.html).
